### ISSUE TITLE
Remove Faraday in favor of pure net http

### ISSUE THREAD

**Issue by derrickreimer** [DripEmail/drip-ruby#20] opened 2016-12-27 19:45 UTC

**Comment by rkcudjoe** [comment] 2016-12-28 14:59
Why, any issues in particular? Because I've been using that to build API clients, and teaching others to use that.

**Comment by djreimer** [comment] 2016-12-28 16:30
@rkcudjoe couple of reasons.

1. Mike Perham wrote a good piece called [Kill Your Dependencies](http://www.mikeperham.com/2016/02/09/kill-your-dependencies/), where he specifically uses Faraday as an example of a needless dependency.

2. It's not really actively maintained anymore (1.0 is still yet to be released) and I've run into other dependency issues with Faraday itself as new Ruby versions have been released in the past. Would rather not have that brittleness when it's really not needed.

**Comment by rkcudjoe** [comment] 2017-06-23 17:46
@djreimer would you recommend using httpparty? Or net http is the only viable option.

**Comment by gma** [comment] 2018-01-17 14:21
I wouldn't use httparty here myself. Given that you want to make it easy for people to include `drip-ruby` in their apps, I always recommend using code in Ruby's standard library instead of third party libraries, so long as the standard library alternative is functional. It doesn't really matter how nice the third party library's API is, the standard library wins every time.

Let me explain.

I'm working on a large Rails app for a company that uses Drip. A couple of weeks ago a colleague upgraded `drip-ruby` from version 0.0.10 to version 1.0.0, hoping that it might fix a few errors we've experienced when parsing JSON returned by the Drip API.

Meanwhile, on another branch, I'd been working on upgrading all the gems in the Rails app's `Gemfile`. It's a big branch, with over 90 commits on it (there's one commit for each upgraded gem).

When I tried rebasing my branch against `master`, I encountered trouble with the upgrade to `drip-ruby` 1.0.0. It requires a version of `faraday` that's >= 0.13.0. This Rails app of ours uses at least 4 gems that conflict with that dependency. One of them explicitly states that it won't work with `faraday` unless the version is < 0.13.

When I ran `bundle update names-of-gems-involved...` I found that Bundler was forcing me to downgrade these other 4 gems, in one case to a very old version that didn't happen to be quite so picky about which version of `faraday` it depended on.

I've had to downgrade to `drip-ruby` 0.0.11 in order to move forward, though this only worked as that version isn't so picky about which version of `faraday` it's compatible with.

The big problem here is the time it takes to work around these kind of problems. In order to work out what to do I had to step through the commit logs of multiple projects, re-run a large test suite plenty of times, and step through multiple versions of `drip-ruby` with a debugger. And once I'd identified the cause (`gem dependency foo --reverse-dependencies` is very useful for that) my first attempt at a solution generated a whole host of new problems…

All in, it took me 24 hours to downgrade `drip-ruby` and get the test suite green again.

And now we can't upgrade this Rails app to the latest version of `drip-ruby`, due to its dependency on `faraday`. For the moment that's okay, as we don't need any of the functionality that's been added since 0.0.10. If/when we do, we're going to have a problem (though relaxing the specificity of the dependency on `faraday` would fix this in our case, if that's feasible?).

Another way of expressing the argument for preferring code in Ruby's standard library (that I hope will now make sense) is that when you depend on a version of a third party library, you couple the versions of your gem that your users can install, to a long (and unknown) list of other gems that your customers also need to use.

What makes the dependency nightmare worse (when writing code for others to consume) is that the problems occur at scale. We'll never know how many others have struggled to resolve dependency conflicts related to `faraday` and `drip-ruby`, but I won't be the last. Nor would I have known to come and mention it here, had another colleague not sent me a link to this issue (i.e. you probably don't hear when it happens).

I hope this makes sense, and is helpful. And if I may, could we request a relaxation in the dependency on `faraday`? I've not checked if a version >= 0.13 is really required, but if not, changing that to the lowest version that will work is likely to save a significant number of people a lot of time.

**Comment by djreimer** [comment] 2018-01-17 14:56
@gma sorry for the trouble, sounds like a classic case of "dependency hell." We'll investigate to see if relaxing Faraday is doable here. I'd still like to pull out the dependency all together, for the reasons you expressed. Competing priorities and all that good stuff...

PRs are always welcome if anyone would like to lend a hand!

**Comment by will-in-wi** [comment] 2018-05-29 14:42
Closing per https://github.com/DripEmail/drip-ruby/pull/39

**Closed by will-in-wi** 2018-05-29 14:42 UTC
